---
kind: pipeline
name: rustfmt

trigger:
  branch:
    - main
  event:
    - custom
    - push
  status:
    - success

steps:
  - name: rustfmt
    image: alpine
    pull: always
    commands:
      - apk add rustup
      - rustup-init -qy --default-host x86_64-unknown-linux-musl --default-toolchain none </dev/null
      - source $CARGO_HOME/env
      - rustup toolchain install nightly --profile minimal --component rustfmt
      - cargo -V
      - cargo fmt -- -V
      - cargo fmt -- --check -l
  
  - name: notify
    image: drillster/drone-email
    pull: always
    settings:
      host: smtp.migadu.com
      username: noreply@drone.msrd0.eu
      from: noreply@drone.msrd0.eu
      password:
        from_secret: SMTP_PASSWORD
    when:
      status:
        - failure

environment:
  CARGO_HOME: target/cargo

...
