# -*- eval: (cargo-minor-mode 1)

[package]
name = "healthcheck"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
attohttpc = { version = "0.17", default-features = false }

[profile.release]
lto = true
opt-level = "z"
